---
- name: Refresh apt cache
  listen: update & upgrade
  ansible.builtin.apt:
    update_cache: true

- name: Dist upgrade
  listen: update & upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
