---
- name: Grant sudo to admins group
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^%admins\s+ALL=\(ALL\)\s+ALL$
    line: "%admins ALL=(ALL) ALL"
    state: present
    validate: visudo -cf %s
