---
- name: Add ssh keys
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    state: present
  loop: "{{ vault_admins | dict2items }}"
  no_log: true

- name: Remove ssh keys from root
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    state: absent
  loop: "{{ vault_admins | dict2items }}"
  no_log: true
