---
proxmox_node: sanctum
primary_admin:
ssh_port:
ansible_port: "{{ ssh_port }}"
ansible_user: "{{ primary_admin }}"

repositories:
  - deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

repositories_removed:
  ceph: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
  pve-enterprise: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
