- name: Configure Proxmox host
  hosts: proxmox
  remote_user: root
  become: true

  tasks:
    - name: Configure Proxmox repository
      lineinfile:
        path: /etc/apt/sources.list
        line: "# deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        create: yes

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: true

    - name: Install VM tools
      package:
        name: libguestfs-tools
        state: latest